### ISSUE TITLE
Define unified strategy for tests with large memory allocations

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#1212]
Thrust/CUB have tests that allocate large amounts of memory that can cause OOM errors on some systems.

We have different approaches for how we handle these situations.

Thrust tests use an approach where they just allocate in a `try/catch` to look for `bad_alloc` and skip to the next smaller input size.

@gevtushenko mentioned that this can lead to issues on Tegra systems where requesting too large an allocation can hang the system instead of throwing `bad_alloc`. 

@gevtushenko suggested an approach where we query the amount of available memory and base the input sizes based on that information. 

Note: CUB device radix sort tests used an approach where they queried the _total_ amount of memory (opposed to _free_). Which doesn't really make sense. 

The goal here is decide among:
1. Use try/catch exception-based strategy (assuming this works reliably on Tegra, maybe disable swap?)
2. Use query free memory strategy
3. Disable "large" tests on Tegra (how do we define what is large?)

**Comment by jrhemstad** [comment]
@gevtushenko to provide an overview of his idea using an abstraction for querying the amount of memory and doing the allocations.

**Comment by gevtushenko** [comment]
Initially, I tried to rely on try/catch approach in the merge sort tests. Unfortunately, it leads to a couple of issues:

1) It leads to slow execution in CI, because `std::bad_alloc` operates in the domain of virtual memory. On some systems, there's less host memory than device one. When the test leads to spilling some memory into swap, it doesn't trigger `std::bad_alloc`, causing the test to run for hours instead of minutes. 
2) Some systems non-deterministically hang before throwing `std::bad_alloc`.

We can try to address those issues by estimating the required storage and checking if system has enough resources. To have a single source of truth for memory estimation / allocation, `cub::detail::temporary_storage::layout` can be helpful:

```cpp
  cub::detail::temporary_storage::layout<2> h_storage_layout;

  auto h_keys_slot = h_storage_layout.get_slot(0);
  auto h_values_slot = h_storage_layout.get_slot(1);

  auto h_keys = h_keys_slot->create_alias<int>(42);
  auto h_values = h_values_slot->create_alias<double>();

  if (pairs) {
    h_values.grow(24);
  }

  if (enough_host_memory(h_storage_layout.get_size())) {
    thrust::host_vector<std::uint8_t> h_storage(h_storage_layout.get_size());
    h_storage_layout.map_to_buffer(thrust::raw_pointer_cast(h_storage.data()), h_storage.size());

    std::cout << h_keys.get() << std::endl;
    std::cout << h_values.get() << std::endl;
  }
```

We can use this helper for both host and device allocations as well as using staging API approach (one invocation of the test to compute storage size, one to execute the test) like we do in CUB. One issue is that the layout is not owning, which makes integration with thrust vectors complicated. Following this path might require getting rid of thrust vectors in our tests. Given that thrust vectors introduce a significant portion of the build time, implementation of thin vector-like container abstraction might make sense.

**Comment by allisonvacanti** [comment]
We'd need some way to incorporate `temp_storage` allocations into this as well, which would take some significant refactoring of the generic launch mechanisms.

Discussing with @jrhemstad, we may also investigate ways to disable swap on a per-process basis to prevent the hangup issues and stick with the simpler exception-based approach.

**Comment by allisonvacanti** [comment]
Another possible solution would be to add the free memory checks to a custom allocator to ensure `bad_alloc` is thrown before hitting swap.

**Comment by allisonvacanti** [comment]
Note: `cudaGetMemInfo` excludes swap on tegra:

> The integrated GPU on Tegra shares memory with CPU and other component of the SoC. The free and total values returned by the API excludes the SWAP memory space maintained by the OS on some platforms.

https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g376b97f5ab20321ca46f7cfa9511b978
