### ISSUE TITLE
[BUG]: CTAD is broken for thrust::pair

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#1642]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

Thrust

### Describe the bug

The refactor to make `thrust::pair` [an alias for `cuda::std::pair` ](https://github.com/NVIDIA/cccl/blob/b68256e5b0ce185cda6d50049a532cf8b81a3ecf/thrust/thrust/pair.h#L75-L76)ended up breaking CTAD because CTAD doesn't work for alias templates. 

### How to Reproduce

Try to compile:
```
#include <thrust/pair.h>
auto p = thrust::pair{42,42};
```
yields:
```
<source>(3): error: argument list for alias template "thrust::THRUST_200400_520_NS::pair" is missing
  auto p = thrust::pair{42,42};
```

### Expected behavior

CTAD should work for `thrust::pair`. 

### Reproduction link

https://godbolt.org/z/1s6as73bb

**Comment by bernhardmgruber** [comment]
I had this problem in the past, so here are some thoughts: I could not find an easy solution in C++17, but it works out of the box in C++20 (via [P1021](https://wg21.link/p1021)]. A deduction guide for the alias does not work. The best solution I found back than (for a more complex type) was to inherit instead of alias in C++17, and redefine the public API where necessary:
```c++
namespace thrust {
    template <typename T, typename U>
    struct pair : cuda::std::pair<T, U> { };
    // ... specialize tuple protocol for thrust::pair
}
```
Given the comparable simple implementation of `cuda::std::pair`, we may just have a distinct (duplicate) pair implementation in thrust until C++20.

**Comment by miscco** [comment]
Yeah that is definitely an option. I just hate the additional boilerplate that we need to use.

Mind that we then also need to specialize all of `{cuda::}std::tuple_size` and `{cuda::}std::tuple_element`
