### ISSUE TITLE
[FEA]: Improve binary function objects and replace thrust implementation 

### ISSUE THREAD

**Issue by miscco** [NVIDIA/cccl#1664]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

Currently the binary function objects like `cuda::std::plus` do not universally default their template argument in all standard modes:
```cpp
#if _CCCL_STD_VER > 2011
template <class _Tp = void>
#else
template <class _Tp>
#endif
struct _LIBCUDACXX_TEMPLATE_VIS plus;
```

Furthermore those objects are duplicated in thrust. 

### Describe the solution you'd like

We should replace thrusts versions with an alias declaration and default the `cuda::std` ones universally

**Comment by srinivasyadav18** [comment]
Hi,

I am interested to work on this issue. 

However, I need further context to get started with it. 
I have understood the first part, which is defaulting the template argument universally. 

Regarding replacing the thrust version with an alias declaration using cuda::std, should I be replacing this code 
https://github.com/NVIDIA/cccl/blob/main/thrust/thrust/functional.h#L213-L237
```cpp
template <typename T = void>
struct plus
{
  typedef T first_argument_type;
  typedef T second_argument_type;
  typedef T result_type;

  _CCCL_EXEC_CHECK_DISABLE
  _CCCL_HOST_DEVICE constexpr T operator()(const T& lhs, const T& rhs) const
  {
    return lhs + rhs;
  }
}; 
```

to use cuda::std::plus ?

Thanks!

**Comment by jrhemstad** [comment]
Hey @srinivasyadav18, thanks for your interest in contributing to CCCL!

You are correct. The basic idea would be to do the following:

Before:
```
namespace thrust{
template <typename T = void>
struct plus
{
  typedef T first_argument_type;
  typedef T second_argument_type;
  typedef T result_type;

  _CCCL_EXEC_CHECK_DISABLE
  _CCCL_HOST_DEVICE constexpr T operator()(const T& lhs, const T& rhs) const
  {
    return lhs + rhs;
  }
}; 
}
```

After:
```
namespace thrust {
   template <typename  T = void>
   using plus = ::cuda::std::plus<T>;
}
```

**Comment by srinivasyadav18** [comment]
Hi @jrhemstad,

Thank you providing more context on the issue! 

I have replaced most of the **function objects** in **thrust** to use `cuda::std` one's. 
But, currently I am stuck with replacing **binary_negate** function ([here](https://github.com/NVIDIA/cccl/blob/0e350f631ed43c3b38fd838b210f3226bdfb624a/thrust/thrust/functional.h#L1541-L1568)), also unary_negate. 
As in C++ 20, negators are disabled by default in `cuda::std`. Hence, its not possible to use it. 

Also, the existing `thrust::binary_negate` does not compile because, the `Predicate` **type** does not have any `first_argument_type` or `second_argument_type` nested type, becasue these **functions objects** now use `cuda::std::` one's, which are dervided from `__binary_function` in **[binary_funcion.h](https://github.com/NVIDIA/cccl/blob/0e350f631ed43c3b38fd838b210f3226bdfb624a/libcudacxx/include/cuda/std/__functional/binary_function.h)** that disable `first_argument_type` and `second_argument_type` by default. 

Can you please provide more insights on how to proceed with this issue ? 
Should we disable the **negators** in thrust now, like how `cuda::std` disabled it based on CXX standard ? 

Thanks!

**Comment by jrhemstad** [comment]
@miscco can you answer @srinivasyadav18's questions?

**Comment by miscco** [comment]
@srinivasyadav18 That is indeed unfortunate. 

I would for now suggest to just ignore negate and keep them at is. We can move incrementally if we like

**Comment by bernhardmgruber** [comment]
@srinivasyadav18 how are you getting along? I could use your work, even if it's just partial :)

**Comment by bernhardmgruber** [comment]
I opened a PR to enable the transparent functors (the `= void`) also in C++11: #1851
