### ISSUE TITLE
[BUG]: Thrust/CUB should check that their `CUDA_ARCHITECTURES_RDC` list is non-empty before adding RDC targets.

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#219]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

CUB

### Describe the bug

(**Note:** Thrust/CUB historically conflated "relocatable device code" (RDC) and "CUDA dynamic parallelism" (CDP). References to architectures that do not support "RDC"  are actually referring to architectures that do not support CDPv1)

Certain architectures are filtered out by:
```cpp
list(FILTER CUB_CUDA_ARCHITECTURES_RDC EXCLUDE REGEX "53|62|72|90")
```
It seems that the RDC targets are still added, leading to the following errors:
```
CMake Error in cub/test/CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target
  "cub.cpp17.test.device_select_unique_by_key.cdp_1".


CMake Error in cub/test/CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target
  "cub.cpp17.test.device_select_unique_by_key.cdp_1".

...
```

### How to Reproduce

```bash
./ci/build_cub.sh "clang++" "17" "90"
```

### Expected behavior

CMake configuration works, no RDC targets are added.

**Comment by jrhemstad** [comment]
As @senior-zero reminded me, this can be worked around for now by disabling CDP(RDC) tests with `-DCUB_ENABLE_RDC_TESTS=OFF`.

**Comment by allisonvacanti** [comment]
> We can soften this rough edge by modify the [thrust|cub]_configure_cuda_target CMake functions should check if the filtered arch list is empty when RDC is requested.

Taking a closer look, this wouldn't be as quick a fix as I'd hoped. The targets are already created by the time those functions are called, so we'd need to do quite a bit of CMake refactoring to be able to remove them based on whether the list is populated or not.

We may need to just add our own versions of `add_executable`, etc so we can disable the targets directly, Maybe something like:

```
cub_create_target(<result_var> <target name> <EXECUTABLE|SHARED|STATIC> RDC <ON|OFF> source1 [source2 ...])
```

This could intercept the condition where RDC is requested for a target but the RDC arch list is empty. This adds some complexity by requiring `result_var` to be tested before doing anything with `target_name`, since the target might not exist, so usage would look like:

```
set(sources ....)
set(rdc_enable ...)
set(target_name ...)
cub_add_target(target_added ${target_name} EXECUTABLE RDC ${rdc_enable} ${sources})
if (target_added)
  target_link_libraries(target_name PRIVATE ...)
  # etc etc, misc target config.
endif()
```

@robertmaynard Can you spot a cleaner solution to this sort of issue?

**Comment by robertmaynard** [comment]
I don't think going with a custom `cub_add_target` is a super clean approach to this. It as you pointed out makes all the subsequent logic conditional since the target might not exist.

I think I would go with a pre-amble that factors in `CUB_ENABLE_RDC_TESTS` and the CUDA_ARCHITECTURE values to determine if RDC only tests are possible. If the users asks for `CUB_ENABLE_RDC_TESTS` but with invalid `CUDA_ARCHITECTURES` I would error out.
